# Generated by Django 2.1.7 on 2019-03-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyainData',
            fields=[
                ('SyainId', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('PassWord', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='WorkData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SyainId', models.CharField(max_length=7)),
                ('date', models.DateField(blank=True, null=True)),
                ('StartTime', models.DateTimeField(blank=True, null=True)),
                ('EndTime', models.DateTimeField(blank=True, null=True)),
                ('MorningOffFlg', models.BooleanField(blank=True, null=True)),
                ('AfternoonOffFlg', models.BooleanField(blank=True, null=True)),
                ('UpdStartTime', models.DateTimeField(blank=True, null=True)),
                ('UpdEndTime', models.DateTimeField(blank=True, null=True)),
                ('UpdMorningOffFlg', models.BooleanField(blank=True, null=True)),
                ('UpdAfternoonOffFlg', models.BooleanField(blank=True, null=True)),
                ('UpdFlg', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
